id: P000766
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:01:53.923489
source_metadata:
  id: bdr:W00EGS1016278
  title: གཅོད་ཀྱི་ཆོས་སྐོར
  author: ''
  volumes:
    5999b184411242be82c7fb8309eb0107:
      image_group_id: I00JW501157
      title: ''
      volume_number: 1
      total_pages: 606
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
